### ISSUE TITLE
Implement common traits for structures

### ISSUE THREAD

**Issue by Luro02** [Finnerale/untis-rs#2]
https://rust-lang-nursery.github.io/api-guidelines/interoperability.html

You can derive most of them (Serialize and Deserialize are from Serde):
``` rust
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default, Serialize, Deserialize)]
```
Only Display has to be implemented manually

**Comment by luleyleo** [comment]
Yes, this would definitely make sense

**Comment by luleyleo** [comment]
Thanks!
