### ISSUE TITLE
Can't be build anymore because of yanked crate

### ISSUE THREAD

**Issue by confusedalex** [Finnerale/untis-rs#4]
I would love to use this libary in a project but it can't be build anymore, because the crate `reqwest` needs `native-tls`, which requires a yanked version of `secruity-framework`

Heres my full error:

```
error: failed to select a version for the requirement `security-framework = "^0.1.13"`
candidate versions found which didn't match: 2.8.2, 2.8.1, 2.8.0, ...
location searched: crates.io index
required by package `native-tls v0.1.3`
    ... which satisfies dependency `native-tls = "^0.1.3"` of package `reqwest v0.8.5`
    ... which satisfies dependency `reqwest = "^0.8.5"` of package `untis v0.2.1`
    ... which satisfies dependency `untis = "^0.2.1"` of package `untis-rust-test v0.1.0 (/home/alex/dev/untis-rust-test)`
```

**Comment by luleyleo** [comment]
Yes, I haven't used this crate for years, so all the dependencies are pretty dated. It'll probably require a bit of effort to bring it up-to-date, but it's definitely doable.

**Comment by BaerLKR** [comment]
How would I go about doing so?
What part is the issue. I have read the logs that it gives me but I can't figure it out. It seems like it is the dependency of another dependency. How is this crate the issue?

**Comment by confusedalex** [comment]
If I rember correctly this crate doesnt work anymore because a dependency is outdated. If you update the dependency to a higher version some classes will break.

**Comment by BaerLKR** [comment]
So there is no easy way to fix it by updating dependencies?

**Comment by arnimattr** [comment]
Hey, I just stumbled across this crate because I wanted to Rewrite My [Own Library](https://github.com/arnim279/untis-api-client) In Rust:tm:. I already made everything compile again, but want to add some more improvements before making a PR.
I should be done by tomorrow or friday if nothing goes wrong :D
